backend:
  image: registry.relizahub.com/ff9e82ed-9863-45ec-9332-ad2b42dd6e87-private/rebom-backend
  replicaCount: 1
  regcred: none
frontend:
  image: registry.relizahub.com/ff9e82ed-9863-45ec-9332-ad2b42dd6e87-private/rebom-frontend
  replicaCount: 1
  regcred: none
postgresql:
  image: postgres:14.1
  defaultSecret: true
  replicaCount: 1
  storage: 5Gi
flyway:
  image: flyway/flyway:8.4.4-alpine
ingress:
  minimalIngressEnabled: true
  traefikEnabled: false
  host: localhost

ecr-regcred:
  enabled: false
